# ---- Theme ----
# Kitty nie ma wbudowanego "theme = ..."
# użyjemy ręcznie kolorów (Xcode Dark vibe)

foreground            #d0d0d0
background            #1f1f24
selection_foreground  #000000
selection_background  #ffffff

# Cursor
cursor                #ffffff

# ANSI colors
color0  #1f1f24
color1  #ff5f5f
color2  #5fff87
color3  #ffd75f
color4  #5fafff
color5  #af5fff
color6  #5fffff
color7  #d0d0d0

color8  #5f5f5f
color9  #ff5f5f
color10 #5fff87
color11 #ffd75f
color12 #5fafff
color13 #af5fff
color14 #5fffff
color15 #ffffff


# ---- Font ----
font_family      JetBrains Mono
font_size        16.0

# Wyłączenie ligatur
disable_ligatures always


# ---- Window ----
window_padding_width 14

# dekoracje (auto = jak w KDE)
hide_window_decorations no


# ---- Cursor ----
cursor_shape beam


# ---- Startup ----
# Kitty nie ma "maximize = true" wprost
# ale możesz to osiągnąć przez WM (KDE rule)
remember_window_size  no
initial_window_width  120c
initial_window_height 35c


# ---- Working directory ----
# start zawsze w home
shell_integration enabled