# ~/.config/yazi/yazi.toml
[mgr]
show_hidden = true

[opener]
edit = [
  { run = 'nvim "$@"',      desc = "Neovim",         block = true },
  { run = 'emacs "$@"',     desc = "Emacs GUI",      block = true },
  { run = 'emacs -nw "$@"', desc = "Emacs Terminal", block = true },
  { run = 'vi "$@"',        desc = "Vim",            block = true },
  { run = 'kwrite "$@" &',  desc = "KWrite",         for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Domyślna aplikacja" },
]
reveal = [
  { run = 'dolphin "$1" &', desc = "Dolphin", for = "unix" },
]
extract = [
  { run = 'unar "$1"',    desc = "unar (auto)" },
  { run = 'tar -xf "$1"', desc = "tar" },
  { run = '7z x "$1"',    desc = "7-zip" },
  { run = 'unzip "$1"',   desc = "unzip" },
]
compress = [
  { run = 'tar -czf "${1%/}.tar.gz" "$@"',  desc = "tar.gz" },
  { run = 'tar -cjf "${1%/}.tar.bz2" "$@"', desc = "tar.bz2" },
  { run = 'tar -cJf "${1%/}.tar.xz" "$@"',  desc = "tar.xz" },
  { run = '7z a "${1%/}.7z" "$@"',          desc = "7zip" },
  { run = 'zip -r "${1%/}.zip" "$@"',       desc = "zip" },
]

[open]
rules = [
  { mime = "text/*",                      use = "edit" },
  { mime = "inode/empty",                 use = "edit" },
  { mime = "application/json",            use = "edit" },
  { mime = "application/xml",             use = "edit" },
  { mime = "application/x-sh",            use = "edit" },
  { mime = "inode/directory",             use = "reveal" },
  { mime = "application/zip",             use = ["extract", "open"] },
  { mime = "application/x-tar",           use = ["extract", "open"] },
  { mime = "application/x-7z-compressed", use = ["extract", "open"] },
  { mime = "application/gzip",            use = ["extract", "open"] },
  { mime = "application/x-rar",           use = ["extract", "open"] },
  { mime = "application/x-bzip2",         use = ["extract", "open"] },
  { mime = "application/zstd",            use = ["extract", "open"] },
  { mime = "*",                           use = "open" },
]
